name: Deploy CDK Stack

on:
  workflow_dispatch: # for manual deployment
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Install npm dependencies for Lambdas
        run: |
          cd lambda/processResume
          npm ci
          npm run build
          cd ../researchCandidate
          npm ci
          npm run build
          cd ../researchCandidateTavily
          npm ci
          npm run build
      - name: CDK Deploy
        run: npx cdk deploy --require-approval never
        env:
          REDUCTO_API_KEY: ${{ secrets.REDUCTO_API_KEY }}
          PIPELINE_ID: ${{ secrets.PIPELINE_ID }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          # FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
